config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # get '/index', to: 'lists#index'
  # get '/lists/new', to: 'lists#new'
  # get '/lists/:id', to: 'lists#show'
  # post 'lists', to: 'lists#create'
  root 'lists#index'
  resources :lists, only: [:index, :new, :create, :show, :destroy] do
    resources :bookmarks, only: [ :create ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def article_params
    params.require(:article).permit(:title, :body, :photo)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_lists, only: [:create]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    # @list = List.find(params[:list_id])
    # @bookmark.list = @list
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_lists
   @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All Lists</h1>

<ul class ="card-container">
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<button class="btn"><%= link_to "Add New List", new_list_path%></button>

<%# <%= cl_image_tag("https://res.cloudinary.com/de4yia9u4/image/upload/v1668786354/vpzjuvznnbbv5tqa208w.jpg",
      width: 400, height: 300, crop: :fill) %>

<%# <%= cl_image_tag("https://res.cloudinary.com/de4yia9u4/image/upload/v1668786379/s5vdywtuvhbxmssv8xcz.jpg",
      width: 150, height: 150, crop: :thumb, gravity: :face) %>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

<button><%= link_to "Back", lists_path%></button>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>

<% @list.bookmarks.each do |bookmark| %>
  <%= bookmark.movie.title %>
  <br>
  <%= bookmark.movie.overview %>
  <button class="btn"><%= link_to "Delete",
  bookmark_path(bookmark),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
</button>

<% end %>


<h3>Add movie to list</h3>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit %>
 <% end %>


<button class ="btn"><%= link_to "To All Lists", lists_path%></button>
<button class ="btn"><%= link_to "Delete",
  root_path,
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
</button>